### ISSUE TITLE
사용 불가능한 패스워드에요.

### ISSUE THREAD

**Issue by coccobellof5** [kerus1024/softether-vpn-autosetup#3]
Hi when I try to install from scratch, it immediately gives me this error.

사용 불가능한 패스워드에요.

It does not resolve, why?

**Comment by kerus1024** [comment]
It has occurred to prevent special characters into the shell parameter.

The affected variables are VAR_LOCAL_SEVPN_ADMINPASSWORD and VAR_LOCAL_SEVPN_FIRSTHUB_FIRSTVPNUSERPASSWORD.

This script is not defined for the firstuser.

If firstusers password is not defined, it seems to occur.

I will modify the code so that if it have not defined a new account, it will be not affected.
